import { TypographyOptions } from '@mui/material/styles/createTypography';
import palette from './palette';

const typography: TypographyOptions = {
  // TODO: ? Should we switch all the H* to Proxima Nova font?
  h1: {
    color: palette?.text?.primary,
    fontWeight: 700,
    fontSize: '80px',
    letterSpacing: '-2px',
    lineHeight: '112px',
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
  h2: {
    color: palette?.text?.primary,
    fontWeight: 700,
    fontSize: '60px',
    letterSpacing: '-2px',
    lineHeight: '72px',
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
  h3: {
    color: palette?.text?.primary,
    fontWeight: 700,
    fontSize: '48px',
    letterSpacing: '-2px',
    lineHeight: '56px',
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
  h4: {
    color: palette?.text?.primary,
    fontWeight: 600,
    fontSize: '20px',
    letterSpacing: '0.15px',
    lineHeight: '28px',
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
  h5: {
    color: palette?.text?.primary,
    fontWeight: 600,
    fontSize: '16px',
    letterSpacing: '0.15px',
    lineHeight: '28px',
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
  h6: {
    color: palette?.text?.hint,
    fontWeight: 300,
    fontSize: '11px',
    lineHeight: '20px',
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
  subtitle1: {
    color: palette?.text?.secondary,
    fontWeight: 700,
    fontSize: '16px',
    lineHeight: '28px',
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
  subtitle2: {
    color: palette?.text?.primary,
    fontWeight: 300,
    fontSize: '13px',
    lineHeight: '20px',
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
  bodyLargeBold: {
    color: palette?.text?.primary,
    fontWeight: 700,
    fontSize: '18px',
    lineHeight: '22px',
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
  body1: {
    color: palette?.text?.primary,
    fontWeight: 400,
    fontSize: '16px',
    letterSpacing: '0.15px',
    lineHeight: '19px',
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
  body2: {
    color: palette?.text?.primary,
    fontSize: '15px',
    fontWeight: 400,
    lineHeight: '28px',
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
  button: {
    color: palette?.text?.primary,
    fontWeight: 600,
    fontSize: '14px',
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
  buttonLarge: {
    color: palette?.text?.primary,
    fontWeight: 600,
    fontSize: '16px',
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
  buttonMedium: {
    color: palette?.text?.primary,
    fontWeight: 600,
    fontSize: '14px',
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
  buttonSmall: {
    color: palette?.text?.primary,
    fontWeight: 600,
    fontSize: '13px',
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
  caption: {
    color: palette?.text?.secondary,
    fontWeight: 400,
    fontSize: '12px',
    lineHeight: '19px',
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
  overline: {
    color: palette?.text?.secondary,
    fontSize: '12px',
    fontWeight: 600,
    letterSpacing: '1px',
    lineHeight: '20px',
    textTransform: 'uppercase',
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
  avatarLetter: {
    color: palette?.text?.secondary,
    fontSize: '20px',
    fontWeight: 400,
    letterSpacing: '0.14px',
    lineHeight: '20px',
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
  inputLabel: {
    color: palette?.text?.secondary,
    fontSize: '12px',
    fontWeight: 400,
    letterSpacing: '0.15px',
    lineHeight: '12px',
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
  helperText: {
    color: palette?.text?.secondary,
    fontSize: '12px',
    fontWeight: 400,
    letterSpacing: '0.4px',
    lineHeight: '20px',
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
  inputText: {
    color: palette?.text?.secondary,
    fontSize: '16px',
    fontWeight: 400,
    letterSpacing: '0.15px',
    lineHeight: '19px',
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
  tooltip: {
    color: palette?.text?.secondary,
    fontSize: '10px',
    fontWeight: 500,
    letterSpacing: '0px',
    lineHeight: '14px',
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
  '*': {
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
  text: {
    fontFamily: 'Roboto,-apple-system,BlinkMacSystemFont,sans-serif, helvetica, arial',
  },
};

export default typography;
